### ISSUE TITLE
│ python: can't open file '/home/inventree/manage.py': [Errno 2] No such file or directory      

### ISSUE THREAD

**Issue by AdamHeavens** [laurensramandt/inventree-kubernetes#1]
Hi,

Thanks for putting these together, I have just tried to deploy to test Inventree but get the above error when the init-migrate container is trying to start, all other components started without any issues.

Any ideas?

Thanks

Adam

**Comment by laurensramandt** [comment]
Hi @AdamHeavens , sorry about the late reply.
Does this occur in the app or cache pod?

**Comment by laurensramandt** [comment]
Hi Adam

Thanks for reporting this issue.
It seems like the default workingDir was missing there, which I added now.

Kind regards
Laurens

**Comment by AdamHeavens** [comment]
Thanks,

Still gives me the following error for the init container

python: can't open file '/home/inventree/Inventree/manage.py': [Errno 2] No such file or directory     

Best regards

Adam
